{% set name = "pyFFTW" %}
{% set version = "0.11" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    git_url: https://github.com/pyFFTW/pyFFTW.git
    git_branch: master

build:
  number: 0

requirements:
    build:
        - toolchain
        - cython
        - python
        - setuptools
        - numpy x.x
        - fftw
    run:
        - python
        - numpy x.x

about:
    home: http://hgomersall.github.com/pyFFTW/
    license: BSD or GPL 2
    license_file: LICENSE.txt
    summary: A pythonic wrapper around FFTW, the FFT library, presenting a unified interface for all the supported transforms.

extra:
    recipe-maintainers:
        - grlee77
        - jakirkham
        - jjhelmus
