travis:
  secure:
    BINSTAR_TOKEN: Z91r7uruNaSreIjYLfxD7vw3/ENvNTefJpu6jGY2oQ2Id6qxEo5hzp8Rz1L8BwPZuQzW/1X74AynpnWj+OTYe93E9I+7rqTtLnV1ijpftJxHwMWcU4J1lqaVkarsG6jlcM5xZ2JsRz1fo4ANf3Zfu0yiRnaoeRz9hqPqAm5jRKdTXS5GFBpPauNGYbpeWLc23ku5CeOeECHOe8fuVnVvC9UIXlc1HJxpX9ozyoQPFQ1SegnH/YP06z46pdwZ376Mc0OvWzt3Me/oRGiia7tIwqhXD83TUQ6riSoWZV+7+JfmG0A7QpqMlbcZO6y9KM7E/L5lQIcTsW0EeeS9JUrXLhh7i81LzdgCjfT5dDA9gNl8JEAMZ48vc6hjbZZUufXRq8bDCM1g3L56IUYsRvdmG7HnV+jZPxcN0AwuvdyRPYGbkM7G3KyGstTqkuB5STRbiWIjum2vr1waUobdfqJjkeGRHeNLMQSbg25w+fBG8MV5/G5E83gvv+LsWG3y9vN/zLwnE+Oz7pOCBbQWhUDCFXbtjYew7ZY1Mlo1s7ds3t0R8qlcOj0rUp+7sTXLRFUHSCglMdBfOcWh3LM1kNJHxTOeXk/WcEO5f/A7+juY9wlJ1+hmBm1f6mR3AtR7loZcnx46TzdFvgto9VEOz9cKoQ0w7TyQe9C+i4ghms9pPwU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
